# -*- coding: utf-8 -*-
"""Lab2_HuggingFace_FastAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXc8ShZkOy2dZBQ9oUgjmDuY8-SMWV-Z
"""

# Upgrade pip
!pip install --upgrade pip

# Install required NLP libraries
!pip install transformers datasets sentence-transformers fastai[transformers] torch torchvision torchaudio --quiet

# Optional: Kaggle API
!pip install kaggle --quiet

# Verify installation
import sys, pkgutil

for pkg in ("transformers","datasets","sentence_transformers","fastai","kaggle","torch"):
    print(pkg, "installed:", pkgutil.find_loader(pkg) is not None)

!nvidia-smi

!nvidia-smi

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list -s imdb --max 5

from transformers import pipeline

sentiment = pipeline("sentiment-analysis")

texts = [
    "I loved the new movie! The acting was great.",
    "This product was terrible and broke in one day."
]

results = sentiment(texts)

for t, r in zip(texts, results):
    print(t)
    print("Prediction:", r)
    print()

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-de")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-de")

text = "Machine learning is transforming technology."

input_ids = tokenizer(text, return_tensors="pt").input_ids
outputs = model.generate(input_ids, max_length=100)
translated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(translated_text)

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("sshleifer/distilbart-cnn-12-6")
model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/distilbart-cnn-12-6")

article = """
Artificial intelligence is advancing rapidly.
Large language models are capable of performing complex tasks
such as translation, summarization, and question answering.
"""

input_ids = tokenizer(article, return_tensors="pt", max_length=1024, truncation=True).input_ids
summary_ids = model.generate(input_ids, max_length=60, min_length=20, do_sample=False)
summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print(summary_text)

from transformers import pipeline

# Load Named Entity Recognition pipeline with explicit model
ner = pipeline("ner", model="dbmdz/bert-large-cased-finetuned-conll03-english")

text = "Barack Obama was born in Hawaii and served as President of the United States."

result = ner(text)

print(result)

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    "How do I cook pasta?",
    "Best ways to boil spaghetti",
    "What is the capital of France?"
]

embeddings = model.encode(sentences, convert_to_tensor=True)

print("Embedding shape:", embeddings.shape)

query = "How to make spaghetti?"

q_emb = model.encode(query, convert_to_tensor=True)

scores = util.pytorch_cos_sim(q_emb, embeddings)[0]

for s, score in zip(sentences, scores):
    print(score.item(), s)

from datasets import load_dataset

ds = load_dataset("imdb")

print(ds)

small_train = ds['train'].shuffle(seed=42).select(range(4000))
small_test  = ds['test'].shuffle(seed=42).select(range(2000))

import pandas as pd

train_df = pd.DataFrame(small_train)
test_df = pd.DataFrame(small_test)

from fastai.text.all import *

dls = TextDataLoaders.from_df(
    train_df,
        text_col='text',
            label_col='label',
                valid_pct=0.1,
                    bs=32
                    )

learn = text_classifier_learner(
    dls,
    AWD_LSTM,
    drop_mult=0.5,
    metrics=accuracy
)

learn.fine_tune(1)

from datasets import load_dataset
from transformers import AutoTokenizer

dataset = load_dataset("glue", "sst2")

print(dataset['train'][0])

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_fn(batch):
    return tokenizer(
        batch['sentence'],
        truncation=True,
        padding='max_length',
        max_length=128
    )

tokenized = dataset.map(tokenize_fn, batched=True)

print(tokenized['train'][0])

import csv

texts = [
    "I love this phone. The battery life is excellent.",
    "Worst purchase ever. It stopped working after two days."
]

results = sentiment(texts)

with open("sentiment_results.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["text", "label", "score"])

    for t, r in zip(texts, results):
        writer.writerow([t, r['label'], r['score']])

print("Saved sentiment_results.csv")

